/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'prasad' at '6/19/18 2:21 PM' with Gradle 2.14.1
 *
 * @author prasad, @date 6/19/18 2:21 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
